# Generated by Django 4.0.4 on 2022-05-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('output_name', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=8)),
                ('end_time', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sign', models.CharField(max_length=4)),
                ('url', models.URLField()),
            ],
        ),
    ]
